#!/bin/bash

########################################################################
DATE=`date '+%Y-%m-%d-%H:%M'`
exec > >(tee -i REFERENCE_BUILDER_${DATE}.log)
exec 2>&1
########################################################################

data=../data

for fna in $data/*fna;do
	echo $fna

	# basename of genome	
	genome=${fna%.fna}
	echo $genome
	# input gff file and genes of interest to be selected from contigs
	gff=$data/${genome}_prodigal.gff
	gene=$data/${genome}_selected_contigs.txt
	
	#output ffn file
	ffn=$data/${genome}_GHoINT.ffn

	out=$ffn
        if [ -f $out ]; then
                echo "'$out' exists."
        else
                echo "'$out' is not found."
		python gene_extractor.py \
		       $fna $gff $gene > $ffn	
	fi

done

